### ISSUE TITLE
uplot not defined

### ISSUE THREAD

**Issue by hz2018tv** [leeoniya/uPlot#591] opened 2021-10-03 03:58 UTC
hi, I am getting the following error with latest git tip on some older browsers like chromium. 

uPlot.iife.js:2344 Uncaught SyntaxError: Unexpected token '?'
add-del-series.html:49 Uncaught ReferenceError: uPlot is not defined
    at add-del-series.html:49
(anonymous) @ add-del-series.html:49,

the lines read
  function uPlot(opts, data, then) {
    const self = {
      mode: opts.mode ?? 1,
    };

Did a little search, seems we have a bunch of places using a syntax like this left??right. in functions like uPlot and accScale. I see there is a good reason to use this ES2020 operator, but meanwhile we are losing compatibility with some not-that-old browsers. Is there a workaround? some of the computers in the school lab have to use whatever installed. thanks

**Comment by leeoniya** [comment] 2021-10-03 14:36
duplicate of https://github.com/leeoniya/uPlot/issues/584

> we are losing compatibility with some not-that-old browsers

which browser & version specifically is this?

from what i've seen, all browsers released in the past 12 months suppprt this.

there are still places in the codebase that use my ifNull() helper, but i want to move forward to using  ??, not backward.

**Comment by leeoniya** [comment] 2021-10-03 15:18
i'll consider switching back to using ifNull for a few more releases, but dont treat this as any kind of commitment to supporting old browsers -- of you need that, you'll need to use Babel with appropriate browser targets.

**Closed by leeoniya** 2021-10-03 15:18 UTC

**Comment by hz2018tv** [comment] 2021-10-03 17:01
sorry, didnt see the old 584 discussion.

agree with you that we want to be moving forward with technologies instead of being backward. I believe browsers will either catch up or be phased out. meanwhile, we are facing some compat issues during transition. no biggies, as long as we know what is happening. never used the babel, as trans-compiling sounds no good for performance which this project is good at.

So far for me, the only effected functions are uPlot and accScale in uplot.iife as it is the only js used , I just manually patch those 3 lines with ifNull() and re-minify it. Technically interesting, do we plan on replacing ifNull()s with this operator? what is the real gain like spacing saving or performance? logically I would think we change ifNull() to use this operator internally and still call ifNull elsewhere. I dont know how the underlying js+vm works. just curious.

**Comment by leeoniya** [comment] 2021-10-04 16:10
> as trans-compiling sounds no good for performance which this project is good at

i dont think it would make a big difference in the performance-critical parts of the codebase; those are all written in a style that doesnt need/use any new syntax features.

>  Technically interesting, do we plan on replacing ifNull()s with this operator? what is the real gain like spacing saving or performance?

`ifNull()` is my invention, while `??` is an ECMA standard to do exactly the same thing. `??` has a much better chance of being optimized by V8 and other JS engines in the future. it is also easier to read for others without having to investigate how ifNull works internally. it's no different than migrating a codebase from ajax to fetch, even when they will both work forever and work the same way for many cases.
