### ISSUE TITLE
Occasional locking up in web browser

### ISSUE THREAD

**Issue by danekasper** [leeoniya/uPlot#115] opened 2020-02-03 04:50 UTC
**Issue**: Browser tab can become unresponsive on rapid scale change.
**Environment** 
Chrome Version 79.0.3945.130 (Official Build) (64-bit)
Tested on two different Windows 64-bit instances. 
**Behaviour**
Have not found a reproducible method, other than to say when doing rapid zoom-out zoom in, on both my own test pages and uplot demos (hosted on github) the browser will eventually hang on a change of scale.  No errors in javascript console. Eventually the google chrome: "Oh Snap -something has gone wrong" page will appear and the tab lost. 

Love the library and effort you have put in to be efficient and only deal with the neccessary. Best library since dygraphs I've come accross. I've managed to play around with draw hooks to make some annotations and it seems to be working quite well. I searched the issues and haven't found any reports of this, any tips on debugging the scaling or where the issue could be?

**Comment by leeoniya** [comment] 2020-02-03 06:21
hey @danekasper 

first, make sure you're using the latest version.

open Chrome's devtools and go to the sources panel, then trigger the hanging behavior. while it's hanging but before "Oh Snap", quickly hit Pause in the debugger and it will take you to the place where there's an infinite loop or something.

https://stackoverflow.com/questions/54279206/pause-script-execution-in-chrome-devtools-not-working-as-expected

**Comment by danekasper** [comment] 2020-02-03 07:49
Handy tip I should've known about a long time ago.

Debugger shows there to be an infinite loop in the date axis ticks - line 635 while(l) in function timeAxisTicks(tzDate). I could not get uPlot to crash while using non-date axis' so this could make sense. 

Assuming the only break from the loop is `if (tick$1 > scaleMax) { break; }`
Stepping through it seems tick$1 = 1515420179.707, scaleMax = 1515420179.7114782 at the final infinite loop.

Debugging using https://leeoniya.github.io/uPlot/demos/months.html.

**Comment by leeoniya** [comment] 2020-02-03 19:02
should be fixed now.

the issue is that Date objects are only accurate down to 1ms cannot generate axis tick increments with smaller resolution. i have numeric increments accounted for down to 1e-12 (anything smaller than that may also go for a loop).

this problem occurs pretty far in the processing pipeline relative to the setScale call, so i had to execute the tick increment logic much earlier to be able to bail out of setScale rather than at draw time when it's too late.

related: https://github.com/leeoniya/uPlot/issues/111#issuecomment-581180337

**Comment by leeoniya** [comment] 2020-02-04 00:42
still a bit of work to do...

**Comment by leeoniya** [comment] 2020-02-04 07:29
ok, this is fixed.

**Closed by leeoniya** 2020-02-04 07:29 UTC
Labels: bug

**Comment by danekasper** [comment] 2020-02-04 11:44
Tested - fix seems good. Thanks @leeoniya!
