### ISSUE TITLE
Show performance as a chart

### ISSUE THREAD

**Issue by bernhard-hofmann** [leeoniya/uPlot#37] opened 2019-10-29 04:13 UTC
Show a chart of the performance comparison in the readme. The readme has a table of values that would be easier to compare and see the differences in a chart. I hear uPlot might be good for that sort of thing. 😄

**Comment by leeoniya** [comment] 2019-10-29 04:20
the problem is that it's not a trendline. looks like a job for #9 :D

**Comment by leeoniya** [comment] 2019-10-29 21:44
i'm gonna close this since i re-bench fairly often and even if there was a way to generate bar charts for comparison, that's extra maintenance unless it's automated.

the table concisely communicates a lot of info, but you'd need several charts to do the same. hopefully potential users can readily differentiate a pre-sorted table and feel the difference in the provided benchmarks.

**Closed by leeoniya** 2019-10-29 21:44 UTC

**Comment by leeoniya** [comment] 2020-03-09 17:57
here you go: https://leeoniya.github.io/uPlot/demos/multi-bars.html
