### ISSUE TITLE
Error with cursor sync

### ISSUE THREAD

**Issue by b4git** [leeoniya/uPlot#507] opened 2021-04-28 16:52 UTC
Hi, lately,  after I downloaded the most recent version (1.6.8) of uPlot.iife.js, I'm receiving an error related to cursor sync with the uPlot.iife.js (renamed to uPlot.js in the screenshot). I am finding difficult to track if something changed in my code or if it is due to some changes in the library code. 

![image](https://user-images.githubusercontent.com/63267629/116442258-e7b44f80-a817-11eb-8d6b-d67a3e9a3837.png)

![image](https://user-images.githubusercontent.com/63267629/116442919-ac665080-a818-11eb-87b8-f3b5d0290e15.png)

**Comment by leeoniya** [comment] 2021-04-28 16:59
yep, i think i have that fixed locally already. i'm refactoring a bunch of the sync code now. i'll have some more commits pushed later today.

**Comment by b4git** [comment] 2021-04-28 17:03
Thanks!

**Comment by leeoniya** [comment] 2021-04-28 17:04
just pushed some changes that should fix it.

**Comment by leeoniya** [comment] 2021-04-29 14:31
gonna close this since this is not a bug in a released version, and should be fixed already on master. try it and let me know.

**Closed by leeoniya** 2021-04-29 14:31 UTC
