### ISSUE TITLE
uPlot causes TypeError on active scrolling with wheel-plugin

### ISSUE THREAD

**Issue by ALEUT** [leeoniya/uPlot#195] opened 2020-05-04 07:19 UTC
Hi!

I got several times similar error on scrolling:
![image](https://user-images.githubusercontent.com/4101909/80943725-861df880-8df0-11ea-995b-422db62fed54.png)

Unfortunately I don't have idea how to reproduce it each time.

**Comment by leeoniya** [comment] 2020-05-04 17:31
first, update to v1.0.8 (just in case).

then add a `incrSpace == null` conditional breakpoint [1] to `incrSpace.push(...` and give me the arguments that get passed to `getIncrSpace(...)`. you can also walk up the stack and see what's going on above.

[1] https://developers.google.com/web/updates/2015/07/set-a-breakpoint-based-on-a-certain-condition

**Comment by ALEUT** [comment] 2020-05-04 19:21
@leeoniya version is 1.0.8

axis:
```
{
  "type": "y",
  "show": true,
  "scale": "y",
  "gap": 5,
  "size": 50,
  "labelSize": 0,
  "labelFont": [
    "bold 18px -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, \"Noto Sans\", sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", \"Noto Color Emoji\"",
    18
  ],
  "side": 3,
  "grid": {
    "show": true,
    "stroke": "rgba(0,0,0,0.07)",
    "width": 2
  },
  "ticks": {
    "show": true,
    "stroke": "rgba(0,0,0,0.07)",
    "width": 2,
    "size": 10
  },
  "font": [
    "18px -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, \"Noto Sans\", sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", \"Noto Color Emoji\"",
    18
  ],
  "_pos": 50
}
```
min: NaN
max: NaN
fullDim: 533

It was called in `drawAxesGrid`:
![image](https://user-images.githubusercontent.com/4101909/81004557-3f161e80-8e55-11ea-92a1-5129a6268c0b.png)

**Comment by leeoniya** [comment] 2020-05-04 20:34
ok, we need to see why `.posToVal()` is returning `NaN` on the `y` scale when given a valid/numeric `top`.

you'll want to put some breakpoints in one or both of these places to figure out why the math ends up with `NaN`:

https://github.com/leeoniya/uPlot/blob/e1509e9fd3fcce4740ef9c5b49b1a6de2f48cb1a/src/uPlot.js#L1478

https://github.com/leeoniya/uPlot/blob/e1509e9fd3fcce4740ef9c5b49b1a6de2f48cb1a/src/uPlot.js#L1463-L1470

**Comment by ALEUT** [comment] 2020-05-05 07:14
@leeoniya 
![image](https://user-images.githubusercontent.com/4101909/81042627-36efca80-8eb9-11ea-9d51-33b76c2eabce.png)

**Comment by ALEUT** [comment] 2020-05-05 07:41
@leeoniya could the reason this line of the code?
```
} else if (k != xScaleKey) {
          wsc.min = inf;
          wsc.max = -inf;
        }
```

**Comment by leeoniya** [comment] 2020-05-05 16:26
> @leeoniya could the reason this line of the code?

it resets the y scales so they can be re-determined from the series data within the new x range.

i0 and i1 are adjacent, but that doesnt tell me much, since they're just the x min/max indices and we're getting the error on the y scale, not the x scale.

you can attach the whole dataset and js code here and i'll try to repro it. without that i'm afraid that i cannot continue debugging like this, it's too time-consuming :(

**Comment by ALEUT** [comment] 2020-05-05 16:30
@leeoniya 
I was able to reproduce it even on the demo:
![image](https://user-images.githubusercontent.com/4101909/81090690-ccfe1200-8f06-11ea-959c-04b2c6c31be1.png)

**Comment by leeoniya** [comment] 2020-05-05 16:58
ah ok, got it. the repro requires drag-zooming into a region with no data. and then trying to wheel-zoom.

the when the y scales are determined from the data in the view, what should they be when there is no data in the view? i don't know.

one solution is to prevent zooming to areas with no data. you can scan the data in the x range and either allow or bail out. see https://github.com/leeoniya/uPlot/issues/187. you can also do this as a plugin which modifies the passed opts with a custom `scales.y.range`.

another route is to tweak the wheel zoom plugin to fall back to some default ymin/ymax if the ones it pulls from `u.scales.y` return `Infinity`.

or you can disable drag zooming via `cursor.drag = {x: false, y: false, setScale: false}`

i cannot think of a generic solution though.

**Comment by ALEUT** [comment] 2020-05-06 07:28
@leeoniya applied simple fix for now:
```
// fix for case when we have area without values and nyMin and nyMax have Infinity value
          if (!Number.isFinite(nyMin) || !Number.isFinite(nyMax)) {
            return;
          }

          u.batch(() => {
            u.setScale("x", {
```

**Comment by leeoniya** [comment] 2020-05-06 13:17
ok. i'm gonna close this since i dont think there's anything to do here besides explain the cause.

wheel zoom does bi-directional zooming without autoscale while the default zooming has autoscale along y. you can disable y auto-scale and/or make drag-zooming bi-directional via `cursor.drag: {x: true, y: true, setScale: true}`, it will behave similarly to wheel zoom.

the simplest solution is to either use wheel zoom or drag zoom but not both, else handle their interop yourself.

**Closed by leeoniya** 2020-05-06 13:17 UTC
Labels: discussion, plugin
