### ISSUE TITLE
Demo Ranger grips are removed when clicking on chart

### ISSUE THREAD

**Issue by lucianbaciu** [leeoniya/uPlot#1014] opened 2024-10-23 13:39 UTC
The issue can be easily reproduced on:
https://leeoniya.github.io/uPlot/demos/zoom-ranger-grips.html

When clicking outside of the selection, it dissapears.

If this is the desired behavior? are there workarounds?

**Comment by leeoniya** [comment] 2024-11-01 21:39
hmm, this regressed in 69bbad5bd00e84f6b45e8c0236e251de65374e45

**Comment by leeoniya** [comment] 2024-11-01 22:30
looking at what i was working on around the same time in Grafana, https://github.com/grafana/grafana/pull/72163 looks like it may have been related.

**Comment by leeoniya** [comment] 2024-11-01 23:34
duplicate of https://github.com/leeoniya/uPlot/issues/936

**Closed** 2024-11-01 23:37 UTC
Labels: bug

**Comment by leeoniya** [comment] 2024-11-01 23:41
i've reverted the relevant change and will test in Grafana to make sure it does not cause any breakage.

**Comment by lucianbaciu** [comment] 2024-11-02 20:45
Thank you!
