### ISSUE TITLE
Setting legend.live to false and toggling a series fails

### ISSUE THREAD

**Issue by doot0** [leeoniya/uPlot#506] opened 2021-04-28 16:23 UTC
When I attempt to toggle a series after setting legend.live to false, it fails with the following error;

```
uPlot.esm.js:3743 Uncaught TypeError: Cannot read property 'parentNode' of undefined
    at toggleDOM (uPlot.esm.js:3743)
    at setSeries (uPlot.esm.js:3767)
    at eval (uPlot.esm.js:2411)
    at HTMLTableCellElement.eval (uPlot.esm.js:1041)
```

I have attempted to call `setSeries` manually instead of using the legend buttons and I get the same issue.

I am using version 1.6.8 of uPlot.

I'm not doing anything that is wildly out of scope for what uPlot's capabilities are so I am having trouble creating a reduced test case, but would like to help get this sorted. I wanted to avoid a situation wherein I had to recreate series toggling manually, but after resorting to that and seeing `setSeries` fail anyway I'm at a loss. 

Thanks.

**Comment by leeoniya** [comment] 2021-04-28 17:01
i think this is a duplicate of https://github.com/leeoniya/uPlot/issues/496

**Comment by doot0** [comment] 2021-04-28 17:25
Based on the `parentNode` error and the fact that `legendRows[i]` contains empty arrays when I check it with debugger I think you're right, though I did see that issue before and noticed it was closed so I created this one. Sorry if it's a bother.

**Comment by leeoniya** [comment] 2021-04-28 17:26
no problem. new release should be out by end of this week.

**Comment by doot0** [comment] 2021-04-28 17:26
Legend, cheers.

**Closed by leeoniya** 2021-04-28 17:26 UTC

**Comment by leeoniya** [comment] 2021-04-28 17:28
pun :100:

**Comment by doot0** [comment] 2021-04-28 17:28
I _genuinely_ didn't intend to do that ahahahaha
