### ISSUE TITLE
Localized date/time formatting

### ISSUE THREAD

**Issue by Christian-Sander** [leeoniya/uPlot#596] opened 2021-10-07 13:13 UTC
I'm wondering if it is possible to use localized date/time formatting in axis and legend labels.

If I create a formatter that uses Intl.DateTimeFormat, I will loose the smart formatting where the first tick prints the full date and the other ones print with finer resolution, e.g. seconds.

Is there a way to retain this behaviour and still have localized date/time formatting, for example by specifying different formatters for different time resolutions?

**Comment by leeoniya** [comment] 2021-10-08 22:40
closing this as a duplicate of #474. please continue work/discussion there.

**Closed by leeoniya** 2021-10-08 22:40 UTC
