### ISSUE TITLE
uPlot charts drawn in timer does not always show up on screen  

### ISSUE THREAD

**Issue by skang** [leeoniya/uPlot#375] opened 2020-11-25 05:32 UTC
When a page contains a lot of (>=40) uPlot.js charts, it might cause the browser to stop responding, or even not showing some of the charts in mobile browsers (especially so in mobile safari). 

To mitigate this issue, one of the trick is to delay the chart rendering in a timer event. But I found that charts drawn in a timer does not always show up on screen. Weirdly, usually only half of the charts show up.  If I replace uPlot.js chart drawing script to a few lines of simple canvas drawing, this problem does not exist.

**Comment by leeoniya** [comment] 2020-11-25 05:35
this is not enough informatiin for me to help you. i do not have apple or ios devices to test with.

please provide a demo or code that triggers the issue.

**Comment by skang** [comment] 2020-11-25 06:01
creating a repo on codesandbox.io now ... will be back soon :)

BTW, I used and liked Flot a lot until I ran into uPlot, I'm very very very impressed at the speed of uPlot.

**Comment by skang** [comment] 2020-11-26 06:03
Sorry, it took me much longer to reproduce the problem in a simpler app.  Please see codesandbox sample next.js app below:

https://codesandbox.io/s/angry-maxwell-xq4m5

If you open the web page (https://xq4m5.sse.codesandbox.io/) in an iphone 6+, you'll see some of the charts does not render fully.   The situation in my real app is much worse, I even see missed charts when # of charts > 50.  For a single page app that resides in memory in a long-running session, I could imagine that the problem will rise sooner or later, no matter how much more memory the device has.

I guess the issue might be caused by memory limitation on ios Safari. But somehow I could not get around this problem by "detroy" charts outside of viewport. I wonder if the memory used by destroyed charts is actually reclaimed by the browser. Your insight on this would be really appreciated!

**Comment by skang** [comment] 2020-11-26 06:13
More words on why I render the charts in a timer - in situation when a lot of charts are needed in an app, rendering all the charts at page loading will significantly delay the response time to user interaction. Scheduling the rendering of charts outside of the viewport seems to be the answer.

**Comment by leeoniya** [comment] 2020-11-26 07:44
thank you for the demo, however, i'm not seeing any issues in Chrome.

i don't have an iphone to test with, but i think this is a dupe of https://github.com/leeoniya/uPlot/issues/163 - you're likely running into the limits of the hardware. i'm not sure why using setTimeout would help the whole situation, though it may allow the first charts to load more reliably. since it is impossible to actually view hundreds of charts at once on a screen that size, i'd recommend doing a lazy load onscroll or some kind of pagination or segmentation/grouping of the charts. ultimately, i don't think this is something that uPlot can solve.

it also looks like you're using an older version of uPlot. uPlot's rendering strategy has changed recently to be async/batched, so you can try upgrading and see if that helps.

were you able to load this amount of data at once with Flot on the iphone?

**Closed** 2020-11-27 08:22 UTC

**Comment by skang** [comment] 2020-11-28 15:38
Thank you very much for looking into this problem. 

As you said, I'm definitely running into the limits of the hardware, which will definitely happen on cellphones, even laptops because of the long running character of my app (SPA), sometime a user might keep the apps running for weeks. Pagination won't meet the need, but lazy loading onscroll (& destroying) is what I'm trying now. Hopefully I'll fix the problem this way. Again thank you very much for your valuable advice on my issue, and I also definitely appreciate your wonderful work of uPlot.js - the fastest charting library I've seen so far. 

I didn't try Flot on this project because of lack of a required functionality on Flot. But I might give it a try later and see if this problem happens with Flot. Will update you once I got sth.

**Comment by leeoniya** [comment] 2020-11-28 16:00
thanks! good luck!
