### ISSUE TITLE
Namespace 'uPlot.Series.Points' has no exported member 'Paths'

### ISSUE THREAD

**Issue by urbanisierung** [leeoniya/uPlot#554] opened 2021-07-25 05:22 UTC
Version: `1.6.14`

Getting a typescript error by using uPlot in my Angular Project:

```bash
Error: node_modules/uplot/dist/uPlot.d.ts:704:19 - error TS2694: Namespace 'uPlot.Series.Points' has no exported member 'Paths'.

704    paths?: Points.Paths;
```

Fixed it for me locally, but would be great to have it fixed in the package itself. Thanks!

**Comment by leeoniya** [comment] 2021-07-25 05:33
duplicate of https://github.com/leeoniya/uPlot/issues/55

fixed in master already, patch release coming in next few days.

**Closed by leeoniya** 2021-07-25 05:33 UTC

**Comment by tlaverdure** [comment] 2021-09-15 19:44
@leeoniya any update on when a new patch will be released? I had to add `"skipLibCheck": true` to my compiler options because I kept running into typing issues.

**Comment by leeoniya** [comment] 2021-09-15 20:02
1.6.15 has the fix for this: https://github.com/leeoniya/uPlot/compare/1.6.14...1.6.15

**Comment by tlaverdure** [comment] 2021-09-15 20:05
I'm getting this error now with `1.16.15`
```
Error: node_modules/uplot/dist/uPlot.d.ts:797:10 - error TS2304: Cannot find name 'GapsRefiner'.

797     gaps?: GapsRefiner;
```

**Comment by leeoniya** [comment] 2021-09-15 20:10
ah, yeah that was fixed in https://github.com/leeoniya/uPlot/issues/564.

1.6.16 is gonna be out today, actually. can you plz double-check if current `master` works for you without errors (in case i missed something again)?

**Comment by tlaverdure** [comment] 2021-09-15 20:27
Unfortunately, it doesn't look like I can run it off `master`.

```
You may need an additional loader to handle the result of these loaders.
| function uPlot(opts, data, then) {
|       const self = {
>               mode: opts.mode ?? 1,
|       };
```

Maybe `opts.mode || 1`?

**Comment by leeoniya** [comment] 2021-09-15 21:30
i am starting to use widely-supported JS features, so if older browser targets are needed, people will need to use Babel or other converters i do not intend to maintain old browser compatibility. `||` was always a hack around a lacking `??` sugar in JS, it's time the world moves on:

https://caniuse.com/mdn-javascript_operators_nullish_coalescing

Opera Mobile (Android) actually has supported `??` for a long time, v63 is based on Chromium 89: https://www.apkmirror.com/apk/opera-software-asa/opera/opera-63-3-3216-58675-release/. i also just tested it and it loads the uPlot benchmark from github without tissues.

**Comment by tlaverdure** [comment] 2021-09-15 21:36
I'm with you on that. Just wasn't able to run it to test it out. 

I have a more modern branch of my project though. Once I installed there everything looks good. This should be good to go 👍

**Comment by denyaalt** [comment] 2021-09-24 22:00
There are many users who have old smartphones.
It is very bad practice to add features that do not work on older smartphones...
